import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "../components/Navbar";
import Starfield from "../styles/Starfield";
// import Footer from "../components/Footer";
import Footer from "../components/FooterBawah";
import TechMarquee from "../components/TechMarquee"; // ✅ gunakan relative path agar konsisten

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Andre Universe",
  description: "Generated by MAW",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Background gradient + starfield */}
        <div
          className="relative min-h-screen flex flex-col"
          style={{
            backgroundImage:
              "linear-gradient(135deg, rgb(6 10 25) 0%, rgb(14 23 47) 50%, rgb(88 60 189) 100%)",
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
          }}
        >
          {/* Layer bintang */}
          <Starfield />

          {/* Konten utama */}
          <div className="relative z-10 flex flex-col min-h-screen">
            <Navbar />

            {/* Main content */}
            <main className="flex-grow">
              {children}
              <TechMarquee /> {/* ✅ Muncul sebelum Footer */}
            </main>

            {/* Footer di paling bawah */}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
